#!/bin/bash
# Genetic Variance Analysis


plink --bfile qc_final \
  --within clusters.txt \
  --fst \
  --out fst

# Notes:
# - Use clusters.txt for overall, pairwise, or one-vs-all FST by modifying cluster assignments.
