#!/bin/bash
# GWAS Analysis: One-vs-All Case-Control Studies

# Perform GWAS for each cluster
for i in {1..4}; do
  pheno_file=${phenotype_files[$((i-1))]}
  plink --bfile $bfile \
        --logistic \
        --pheno $pheno_file \
        --covar $covar_file \
        --allow-no-sex \
        --adjust \
        --out ${output_prefix}_cluster${i}
done

# Note:
# - Each PLINK assoc output file is used as the input for FUMA (v1.6.0; https://fuma.ctglab.nl/).
# - SNP2GENE and GENE2FUNC functions were employed with default parameters, except for 1KGP-EAS as the reference panel.
